### ISSUE TITLE
Wrong permissions on linked directories

### ISSUE THREAD

**Issue by chalasr** [manala/ansible-role-files#5]
@nervo First, many thanks for the feature introduced in #3, we are almost good!
The issue I face is that the newly created directory is not writable, neither by the vagrant user nor by symfony itself:

```sh
$ rm -rf var/cache/dev
````
> rm: cannot remove `var/cache/dev/appDevDebugProjectContainer.xml': Permission denied

```sh 
bin/console cache:clear
```

>  [RuntimeException]
  Unable to write in the cache directory (/srv/app/var/cache/dev)

![](http://image.prntscr.com/image/49dfceebbded4e18b9603199c888da3f.png)

Could we do something for that?

**Comment by nervo** [comment]
Hm, i guess that's not the directory itself, but its copied content which is not writable.
Could you confirm that /srv/app/var/cache is just a symlink to /var/cache/app, and that appDevDebugProjectContainer.xml was copied from /srv/app/var/cache when it was not a symlink but a simple directory  ?

Anyway, we should set the same permissions on the directory and its copied content.

**Comment by chalasr** [comment]
>  /srv/app/var/cache is just a symlink to /var/cache/app

Yes it is

> appDevDebugProjectContainer.xml was copied from /srv/app/var/cache when it was not a symlink but a simple directory ?

Not exactly but yes: the `cache` directory has a `dev` sub directory which existed before the provisioning and contains the `appDevDebugProjectContainer.xml` file. It's indeed the copied content permissions which needs to be set, i.e. `[linked_directory]/*`

**Comment by nervo** [comment]
The diagnosis is clear as spring water.

![](https://media.giphy.com/media/agI1cpoQuEOLS/giphy.gif)

**Comment by chalasr** [comment]
As discussed, let's forget this feature as it is endless and too much intrusive.
Please close this after reverting it.

Also, could you please give me the way to set the `force` option to `true` in manalize, so we can close #6 and move on?
