### ISSUE TITLE
Directory linking now fails if the directory is empty

### ISSUE THREAD

**Issue by chalasr** [manala/ansible-role-files#6]
For a project that has a `var/logs` linked directory which is empty:

> fatal: [localhost]: FAILED! => {"changed": true, "cmd": "mv /srv/app/var/logs/* /var/log/app", "delta": "0:00:00.004888", "end": "2016-10-12 17:02:06.520425", "failed": true, "rc": 1, "start": "2016-10-12 17:02:06.515537", "stderr": "mv: cannot stat `/srv/app/var/logs/*': No such file or directory", "stdout": "", "stdout_lines": [], "warnings": []}

After this one and #5, it should be perfect.
💋

**Comment by nervo** [comment]
Ach', an empty one....
